---
- name: Install MySQL 5.7 on Ubuntu
  hosts: all
  become: yes
  vars:
    mysql_public_key: B7B3B788A8D3785C  # Variable for the MySQL public key

  tasks:
    - name: Ensure system is up-to-date
      apt:
        update_cache: yes
        cache_valid_time: 3600  # 1 hour
    
    - name: Install wget if not present
      apt:
        name: wget
        state: present

    - name: Download MySQL APT config (Alternative)
      get_url:
        url: https://repo.mysql.com//mysql-apt-config_0.8.12-1_all.deb
        dest: /tmp/mysql-apt-config_0.8.12-1_all.deb
      tags: mysql config

    - name: Select version os
      shell: echo mysql-apt-config mysql-apt-config/repo-codename select bionic | sudo debconf-set-selections;

    - name: Select version mysql
      shell: echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections;

    - name: Select tools
      shell: echo mysql-apt-config mysql-apt-config/select-tools select Enabled | sudo debconf-set-selections;

    - name: Select preview
      shell: echo mysql-apt-config mysql-apt-config/select-preview select Disabled | sudo debconf-set-selections;

    - name: Select product ok
      shell: echo mysql-apt-config mysql-apt-config/select-product select Ok | sudo debconf-set-selections;

    - name: Install MySQL APT config package
      shell: dpkg -i /tmp/mysql-apt-config_0.8.12-1_all.deb
      environment:
        DEBIAN_FRONTEND: noninteractive
      register: res_apt
      ignore_errors: yes  # In case dpkg fails, we will handle errors

    - name: Dump dpkg result
      debug:
        msg: "{{ res_apt }}"

    - name: Update apt cache after adding MySQL repository
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Add MySQL public key to apt keyring
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: "{{ mysql_public_key }}"
        state: present

    - name: Export MySQL public key and save it to /etc/apt/trusted.gpg.d/mysql.asc
      shell: |
        sudo apt-key export {{ mysql_public_key }} | sudo tee /etc/apt/trusted.gpg.d/mysql.asc
      register: export_key
      ignore_errors: yes

    - name: Dump export key result
      debug:
        msg: "{{ export_key }}"

    - name: Update apt repository
      shell: apt update
      register: apt_update
      ignore_errors: yes  # In case of errors in the update, we will continue

    - name: Dump update result
      debug:
        msg: "{{ apt_update }}"

    - name: Install MySQL client 5.7
      apt:
        name: mysql-client=5.7.42-1ubuntu18.04
        state: present

    - name: Install MySQL community server 5.7
      apt:
        name: mysql-community-server=5.7.42-1ubuntu18.04
        state: present

    - name: Install MySQL server 5.7
      apt:
        name: mysql-server=5.7.42-1ubuntu18.04
        state: present

    - name: Fix broken dependencies if necessary
      apt:
        name: mysql-client=5.7.42-1ubuntu18.04
        state: present
        force: yes

    - name: Ensure MySQL service is started and enabled
      service:
        name: mysql
        state: started
        enabled: yes
